# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-14 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price_Coin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
                ('price_usd', models.CharField(max_length=10)),
                ('price_krw', models.CharField(max_length=10)),
                ('gimp', models.CharField(max_length=10)),
                ('website', models.URLField()), 
            ],
        ),
    ]
