# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-14 13:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_price_coin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='price_coin',
            options={'ordering': ['volume']},
        ),
        migrations.AddField(
            model_name='price_coin',
            name='exchange_rate',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='price_coin',
            name='volume',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
